require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComissionsController do

  # This should return the minimal set of attributes required to create a valid
  # Comission. As you add validations to Comission, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComissionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all comissions as @comissions" do
      comission = Comission.create! valid_attributes
      get :index, {}, valid_session
      assigns(:comissions).should eq([comission])
    end
  end

  describe "GET show" do
    it "assigns the requested comission as @comission" do
      comission = Comission.create! valid_attributes
      get :show, {:id => comission.to_param}, valid_session
      assigns(:comission).should eq(comission)
    end
  end

  describe "GET new" do
    it "assigns a new comission as @comission" do
      get :new, {}, valid_session
      assigns(:comission).should be_a_new(Comission)
    end
  end

  describe "GET edit" do
    it "assigns the requested comission as @comission" do
      comission = Comission.create! valid_attributes
      get :edit, {:id => comission.to_param}, valid_session
      assigns(:comission).should eq(comission)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Comission" do
        expect {
          post :create, {:comission => valid_attributes}, valid_session
        }.to change(Comission, :count).by(1)
      end

      it "assigns a newly created comission as @comission" do
        post :create, {:comission => valid_attributes}, valid_session
        assigns(:comission).should be_a(Comission)
        assigns(:comission).should be_persisted
      end

      it "redirects to the created comission" do
        post :create, {:comission => valid_attributes}, valid_session
        response.should redirect_to(Comission.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comission as @comission" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comission.any_instance.stub(:save).and_return(false)
        post :create, {:comission => {}}, valid_session
        assigns(:comission).should be_a_new(Comission)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comission.any_instance.stub(:save).and_return(false)
        post :create, {:comission => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comission" do
        comission = Comission.create! valid_attributes
        # Assuming there are no other comissions in the database, this
        # specifies that the Comission created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Comission.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => comission.to_param, :comission => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested comission as @comission" do
        comission = Comission.create! valid_attributes
        put :update, {:id => comission.to_param, :comission => valid_attributes}, valid_session
        assigns(:comission).should eq(comission)
      end

      it "redirects to the comission" do
        comission = Comission.create! valid_attributes
        put :update, {:id => comission.to_param, :comission => valid_attributes}, valid_session
        response.should redirect_to(comission)
      end
    end

    describe "with invalid params" do
      it "assigns the comission as @comission" do
        comission = Comission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comission.any_instance.stub(:save).and_return(false)
        put :update, {:id => comission.to_param, :comission => {}}, valid_session
        assigns(:comission).should eq(comission)
      end

      it "re-renders the 'edit' template" do
        comission = Comission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comission.any_instance.stub(:save).and_return(false)
        put :update, {:id => comission.to_param, :comission => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comission" do
      comission = Comission.create! valid_attributes
      expect {
        delete :destroy, {:id => comission.to_param}, valid_session
      }.to change(Comission, :count).by(-1)
    end

    it "redirects to the comissions list" do
      comission = Comission.create! valid_attributes
      delete :destroy, {:id => comission.to_param}, valid_session
      response.should redirect_to(comissions_url)
    end
  end

end
