require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VotoDiputadosController do

  # This should return the minimal set of attributes required to create a valid
  # VotoDiputado. As you add validations to VotoDiputado, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VotoDiputadosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all voto_diputados as @voto_diputados" do
      voto_diputado = VotoDiputado.create! valid_attributes
      get :index, {}, valid_session
      assigns(:voto_diputados).should eq([voto_diputado])
    end
  end

  describe "GET show" do
    it "assigns the requested voto_diputado as @voto_diputado" do
      voto_diputado = VotoDiputado.create! valid_attributes
      get :show, {:id => voto_diputado.to_param}, valid_session
      assigns(:voto_diputado).should eq(voto_diputado)
    end
  end

  describe "GET new" do
    it "assigns a new voto_diputado as @voto_diputado" do
      get :new, {}, valid_session
      assigns(:voto_diputado).should be_a_new(VotoDiputado)
    end
  end

  describe "GET edit" do
    it "assigns the requested voto_diputado as @voto_diputado" do
      voto_diputado = VotoDiputado.create! valid_attributes
      get :edit, {:id => voto_diputado.to_param}, valid_session
      assigns(:voto_diputado).should eq(voto_diputado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VotoDiputado" do
        expect {
          post :create, {:voto_diputado => valid_attributes}, valid_session
        }.to change(VotoDiputado, :count).by(1)
      end

      it "assigns a newly created voto_diputado as @voto_diputado" do
        post :create, {:voto_diputado => valid_attributes}, valid_session
        assigns(:voto_diputado).should be_a(VotoDiputado)
        assigns(:voto_diputado).should be_persisted
      end

      it "redirects to the created voto_diputado" do
        post :create, {:voto_diputado => valid_attributes}, valid_session
        response.should redirect_to(VotoDiputado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved voto_diputado as @voto_diputado" do
        # Trigger the behavior that occurs when invalid params are submitted
        VotoDiputado.any_instance.stub(:save).and_return(false)
        post :create, {:voto_diputado => {}}, valid_session
        assigns(:voto_diputado).should be_a_new(VotoDiputado)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VotoDiputado.any_instance.stub(:save).and_return(false)
        post :create, {:voto_diputado => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested voto_diputado" do
        voto_diputado = VotoDiputado.create! valid_attributes
        # Assuming there are no other voto_diputados in the database, this
        # specifies that the VotoDiputado created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VotoDiputado.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => voto_diputado.to_param, :voto_diputado => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested voto_diputado as @voto_diputado" do
        voto_diputado = VotoDiputado.create! valid_attributes
        put :update, {:id => voto_diputado.to_param, :voto_diputado => valid_attributes}, valid_session
        assigns(:voto_diputado).should eq(voto_diputado)
      end

      it "redirects to the voto_diputado" do
        voto_diputado = VotoDiputado.create! valid_attributes
        put :update, {:id => voto_diputado.to_param, :voto_diputado => valid_attributes}, valid_session
        response.should redirect_to(voto_diputado)
      end
    end

    describe "with invalid params" do
      it "assigns the voto_diputado as @voto_diputado" do
        voto_diputado = VotoDiputado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VotoDiputado.any_instance.stub(:save).and_return(false)
        put :update, {:id => voto_diputado.to_param, :voto_diputado => {}}, valid_session
        assigns(:voto_diputado).should eq(voto_diputado)
      end

      it "re-renders the 'edit' template" do
        voto_diputado = VotoDiputado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VotoDiputado.any_instance.stub(:save).and_return(false)
        put :update, {:id => voto_diputado.to_param, :voto_diputado => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested voto_diputado" do
      voto_diputado = VotoDiputado.create! valid_attributes
      expect {
        delete :destroy, {:id => voto_diputado.to_param}, valid_session
      }.to change(VotoDiputado, :count).by(-1)
    end

    it "redirects to the voto_diputados list" do
      voto_diputado = VotoDiputado.create! valid_attributes
      delete :destroy, {:id => voto_diputado.to_param}, valid_session
      response.should redirect_to(voto_diputados_url)
    end
  end

end
